# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1023dd3bb3aaeb89b70bc1813857ecfc7169176963baff12626e3857bfad98d8fb9b02b0c75353ce72cc740d80407b2b91ae0f21f049fddac0a497296b0b92b

test:
  secret_key_base: 84c4a2b560cf69340e78457c03bba95eb3ad1b0ac642b7fce5cb364f9eab23fdfe4c70dcdb37de2e3bda24b9110230880da543da1f3a0073953a80b8f7dc096b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
